app/models.py
from app import db
from datetime import datetime


class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(32), index=True, unique=True)
    first_name = db.Column(db.String(32))
    last_name = db.Column(db.String(32))
    phone = db.Column(db.String(11), index=True, unique=True)
    creation_time = db.Column(db.DateTime, default=datetime.utcnow)

    emails = db.relationship('Email', backref='contact', lazy='dynamic')

    def __repr__(self):
        return '<Contact {} with id: {}, first_name: {}, last_name: {}, ' \
               'phone: {}, emails: {}, creation:{}>' \
            .format(self.username, self.id, self.first_name, self.last_name,
                    self.phone, self.emails, self.creation_time)

class Email(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(240))
    contact_id = db.Column(db.Integer, db.ForeignKey('contact.id'))

    def __repr__(self):
        return '<Email {}>'.format(self.content)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, Email
from wtforms import ValidationError
from ..models import Contact

class ContactForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    first_name = StringField('First name',
                             validators=[Length(min=0, max=32)])
    last_name = StringField('Last name',
                            validators=[Length(min=0, max=32)])
    phone = StringField('Phone',
                        validators=[Length(min=0, max=11)])

    submit = SubmitField('Add')

    def validate_contact(self, field):
        if Contact.query.filter_by(username=field.data).first():
            raise ValidationError('Contact already registered.')

class SearchForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    submit = SubmitField('Find')

class EmailForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Add')

app/__init__.py
import logging
from logging.handlers import RotatingFileHandler
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import config
from flask_bootstrap import Bootstrap
from redis import Redis
import rq
from celery import Celery
from config import Config

celery = Celery(__name__, broker=Config.CELERY_BROKER_URL)

db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    app.redis = Redis.from_url(app.config['REDIS_URL'])
    app.task_queue = rq.Queue('ozan', connection=app.redis)

    db.init_app(app)
    migrate.init_app(app, db)
    bootstrap.init_app(app)

    celery.conf.update(app.config)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    if not app.debug and not app.testing:

        if app.config['LOG_TO_STDOUT']:
            stream_handler = logging.StreamHandler()
            stream_handler.setLevel(logging.INFO)
            app.logger.addHandler(stream_handler)
        else:
            if not os.path.exists('logs'):
                os.mkdir('logs')
            file_handler = RotatingFileHandler('logs/contact_manager.log',
                                               maxBytes=10240, backupCount=10)
            file_handler.setFormatter(logging.Formatter(
                '%(asctime)s %(levelname)s: %(message)s '
                '[in %(pathname)s:%(lineno)d]'))
            file_handler.setLevel(logging.INFO)
            app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('Contact Manager startup')

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import views, errors, tasks

app/main/views.py
from flask import render_template, flash, redirect, url_for, request
from app import db
from app.main.forms import ContactForm, SearchForm, EmailForm
from app.models import Contact, Email
from app.main import bp
from app.main.tasks import example

@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    return render_template('index.html', title='Home')

@bp.route('/add', methods=['GET', 'POST'])
def add():
    form = ContactForm()
    if form.validate():
        contact = Contact(username=form.username.data,
                          first_name=form.first_name.data,
                          last_name=form.last_name.data,
                          phone=form.phone.data)
        db.session.add(contact)
        db.session.commit()
        flash('Your contact is added!')
        return redirect(url_for('main.index'))

    return render_template('add.html', title='Home', form=form)

@bp.route('/find', methods=['GET', 'POST'])
def find():
    c = None
    form = SearchForm()
    if form.validate_on_submit():
        username = form.username.data
        c = Contact.query.filter_by(username=username).first()

    return render_template('find.html', form=form, contact=c)


@bp.route('/list_contacts', methods=['GET', 'POST'])
def list_contacts():
    contacts = Contact.query.limit(10).all()

    return render_template('list.html', contacts=contacts)

@bp.route('/edit_contact/<key>', methods=['GET', 'POST'])
def edit_contact(key):

    contact =Contact.query.filter_by(id=key).first()
    if contact is not None:
        form = ContactForm(formdata=request.form, obj=contact)

        if request.method == 'POST' and form.validate():
            contact.first_name = form.first_name.data
            contact.last_name = form.last_name.data
            contact.phone = form.phone.data

            db.session.commit()
            flash('Your contact is updated!')
            return redirect(url_for('main.edit_contact',key=key))

    return render_template('contact.html', form = form)

@bp.route('/delete_contact/<key>', methods=['GET', 'POST'])
def delete_contact(key):

    contact =Contact.query.filter_by(id=key).first()

    if contact is not None:
        db.session.delete(contact)
        db.session.commit()
        flash('Your contact was deleted!')
        redirect(url_for('main.list_contacts'))

    contacts = Contact.query.limit(10).all()

    return render_template('list.html', contacts=contacts)

@bp.route('/add_email/<key>', methods=['GET', 'POST'])
def add_email(key):

    contact = Contact.query.filter_by(id=key).first()
    if contact is not None:
        form = EmailForm()

        if form.validate_on_submit():
            email = Email(content=form.email.data,
                              contact_id=key)
            db.session.add(email)
            db.session.commit()
            flash('Your email was added!')
            return redirect(url_for('main.index'))

    return render_template('email.html', title='Home', form=form)


@bp.route('/task', methods=['GET', 'POST'])
def task():
    example.delay(100)
    return render_template('index.html', title='Home')

app/templates/add.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}


{% block title %}
    {% if title %}{{ title }} - Contact Manager {% else %}{{ 'Welcome to Contact Manager' }}{% endif %}
{% endblock %}


{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Contact Manager</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">{{'Home' }}</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">

                    <li><a href="{{ url_for('main.list_contacts') }}">{{'List' }}</a></li>
                    <li><a href="{{ url_for('main.find') }}">{{'Find' }}</a></li>
                    <li><a href="{{ url_for('main.add') }}">{{'Add' }}</a></li>
                    <li><a href="{{ url_for('main.task') }}">{{'Auto' }}</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/contact.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>

    </div>

{% endblock %}

app/templates/email.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/find.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

    <div class="page-header">
    <h1>Contact: {% if contact %}{{ contact['first_name'] }} {{ contact['last_name'] }}
        <br>{{ contact['phone'] }}
        {% else %}Stranger{% endif %}!</h1>
    </div>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

app/templates/list.html
{% extends "base.html" %}

{% block content %}
 <table>
          <tr><th>username</th><th>email</th></tr>
    {% for contact in contacts %}


           <tr><td>{{ contact.username }}</td><td> {% for email in contact.emails.all() %}
                  <small>{{email.content}}<br></small>
                  {% endfor %}</td>
           </tr>

           <tr><td>  <a href="{{ url_for('main.edit_contact', key=contact.id) }}">
                    Edit Contact
                    </a>&nbsp;&nbsp;</td>
               <td>
                   <a href="{{ url_for('main.delete_contact', key=contact.id) }}">
                    Delete Contact
                    </a>&nbsp;&nbsp;

                   <a href="{{ url_for('main.add_email', key=contact.id) }}">
                    Add email
                    </a>
               </td>
           </tr>





    {% endfor %}
      </table>
{% endblock %}